# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: 100

# Settings for ros_control hardware interface
hardware_interface:
   joints:
     - outer_yaw
     - outer_pitch
     - outer_insertion
     - outer_roll
     - outer_wrist_pitch
     - outer_wrist_yaw

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller

pos_based_pos_traj_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - outer_yaw
     - outer_pitch
     - outer_insertion
     - outer_roll
     - outer_wrist_pitch
     - outer_wrist_yaw
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      outer_yaw: {trajectory: 0.1, goal: 0.1}
      outer_pitch: {trajectory: 0.1, goal: 0.1}
      outer_insertion: {trajectory: 0.1, goal: 0.1}
      outer_roll: {trajectory: 0.1, goal: 0.1}
      outer_wrist_pitch: {trajectory: 0.1, goal: 0.1}
      outer_wrist_yaw: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  500
   action_monitor_rate: 10

   # state_publish_rate:  50 # Defaults to 50
   # action_monitor_rate: 20 # Defaults to 20
   #hold_trajectory_duration: 0 # Defaults to 0.5
